"""empty message

Revision ID: 1a9af916efc9
Revises: 
Create Date: 2023-02-04 15:08:24.384372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9af916efc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("create sequence adm_permissions_count_seq start 1 increment 1 no cycle")
    op.create_table('adm_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('a_code', sa.Text(), nullable=False),
    sa.Column('a_desc', sa.Text(), nullable=True),
    sa.Column('qualified_function', sa.Text(), nullable=False),
    sa.Column('a_status', sa.Text(), nullable=False),
    sa.Column('counter', sa.Integer(), server_default=sa.text("nextval('adm_permissions_count_seq')"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('counter')
    )
    with op.batch_alter_table('adm_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adm_permissions_a_code'), ['a_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_adm_permissions_a_desc'), ['a_desc'], unique=False)
        batch_op.create_index(batch_op.f('ix_adm_permissions_a_status'), ['a_status'], unique=True)
        batch_op.create_index(batch_op.f('ix_adm_permissions_qualified_function'), ['qualified_function'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adm_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adm_permissions_qualified_function'))
        batch_op.drop_index(batch_op.f('ix_adm_permissions_a_status'))
        batch_op.drop_index(batch_op.f('ix_adm_permissions_a_desc'))
        batch_op.drop_index(batch_op.f('ix_adm_permissions_a_code'))

    op.drop_table('adm_permissions')
    # ### end Alembic commands ###
